name: Trigger auto deployment for aca-rauw-frontend-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-rauw-frontend-prod-AutoDeployTrigger-30bff62d-d78e-42d3-9836-4aeef7026ea4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACARAUWFRONTENDPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACARAUWFRONTENDPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACARAUWFRONTENDPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: racrrauwfront.azurecr.io
          registryUsername: ${{ secrets.ACARAUWFRONTENDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACARAUWFRONTENDPROD_REGISTRY_PASSWORD }}
          containerAppName: aca-rauw-frontend-prod
          resourceGroup: rg-rauw-frontend-prod
          imageToBuild: racrrauwfront.azurecr.io/aca-rauw-frontend-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


